import { Metadata } from 'next'
import FooterSection from '@/components/landing/FooterSection'

export const metadata: Metadata = {
  title: 'Terms of Service — CareerCoach Pakistan',
  description: 'Terms and conditions for using CareerCoach Pakistan.',
}

export default function TermsPage() {
  return (
    <>
      <main className="min-h-screen bg-white px-4 py-16">
        <div className="mx-auto max-w-3xl">
          <h1 className="mb-2 text-3xl font-bold text-gray-900">Terms of Service</h1>
          <p className="mb-10 text-sm text-gray-500">Last updated: 9 May 2026</p>

          <Section title="1. Acceptance">
            <p>
              By creating an account or using CareerCoach Pakistan (&quot;Service&quot;, &quot;we&quot;,
              &quot;us&quot;), you agree to these Terms of Service. If you do not agree, do not use the
              Service. These terms apply to all users, including free-trial users and paying subscribers.
            </p>
          </Section>

          <Section title="2. Description of Service">
            <p>
              CareerCoach Pakistan is an AI-powered interview preparation platform designed for Pakistani
              job seekers. The Service allows you to paste a job description, answer AI-generated interview
              questions (in English or Urdu), and receive automated feedback and scores.
            </p>
            <p className="mt-3">
              AI feedback is generated by a large language model (LLaMA via Groq) and is provided for
              practice and self-improvement purposes only. It does not constitute professional career
              advice, and we make no guarantee that using the Service will result in employment.
            </p>
          </Section>

          <Section title="3. Free Trial">
            <ul className="list-disc pl-5 space-y-2">
              <li>New accounts receive a <strong>7-day free trial</strong> with full access to all features.</li>
              <li>No credit card is required to start a trial.</li>
              <li>After 7 days, access to the app is restricted until a subscription is activated.</li>
              <li>Each email address is entitled to one free trial. Creating multiple accounts to extend trial access is prohibited.</li>
            </ul>
          </Section>

          <Section title="4. Subscription and Billing">
            <ul className="list-disc pl-5 space-y-2">
              <li>
                The subscription price is <strong>PKR 999 per month</strong>, billed monthly via Stripe.
              </li>
              <li>
                Your subscription renews automatically each month until you cancel.
              </li>
              <li>
                You can cancel at any time from the Billing page inside the app. Cancellation takes effect
                at the end of the current billing period — you retain access until then.
              </li>
              <li>
                We reserve the right to change pricing with 30 days&apos; notice to existing subscribers.
              </li>
            </ul>
          </Section>

          <Section title="5. Refund Policy">
            <p>
              We offer a <strong>7-day money-back guarantee</strong> for new subscribers. If you are not
              satisfied within 7 days of your first payment, email us at{' '}
              <a href="mailto:safdarayub@gmail.com" className="text-[#1E40AF] underline">
                safdarayub@gmail.com
              </a>{' '}
              and we will issue a full refund. After 7 days, payments are non-refundable.
            </p>
          </Section>

          <Section title="6. Acceptable Use">
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Use the Service for any unlawful purpose or in violation of applicable Pakistani law.</li>
              <li>Attempt to reverse-engineer, scrape, or automate access to the Service.</li>
              <li>Share your account credentials with others or resell access to the Service.</li>
              <li>Submit content that is abusive, harassing, defamatory, or infringes third-party rights.</li>
              <li>Attempt to bypass the trial or subscription paywall through technical means.</li>
            </ul>
          </Section>

          <Section title="7. AI-Generated Content">
            <p>
              Interview questions and feedback are generated by an AI model. This content may occasionally
              be inaccurate, incomplete, or outdated. You are responsible for independently verifying any
              technical or career advice before acting on it. We are not liable for decisions you make
              based on AI-generated content.
            </p>
          </Section>

          <Section title="8. Intellectual Property">
            <p>
              The CareerCoach Pakistan name, logo, and software are owned by us and protected by applicable
              intellectual property laws. Your interview answers and job descriptions remain your own content.
              By submitting content, you grant us a limited licence to process it solely for the purpose of
              delivering the Service (e.g., sending it to the AI model to generate feedback).
            </p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>
              To the maximum extent permitted by law, CareerCoach Pakistan and its owners shall not be
              liable for any indirect, incidental, special, or consequential damages arising from your use
              of (or inability to use) the Service, including lost profits or missed job opportunities.
              Our total liability to you for any claim shall not exceed the amount you paid us in the
              three months preceding the claim.
            </p>
          </Section>

          <Section title="10. Disclaimers">
            <p>
              The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of
              any kind, express or implied. We do not warrant that the Service will be uninterrupted,
              error-free, or that AI feedback will be accurate. We reserve the right to modify or
              discontinue the Service at any time with reasonable notice.
            </p>
          </Section>

          <Section title="11. Governing Law">
            <p>
              These Terms are governed by the laws of the Islamic Republic of Pakistan. Any disputes
              shall be resolved in the courts of Lahore, Punjab, Pakistan.
            </p>
          </Section>

          <Section title="12. Changes to These Terms">
            <p>
              We may update these Terms from time to time. We will notify you by email or in-app notice
              at least 14 days before material changes take effect. Continued use of the Service after
              that date constitutes acceptance of the revised Terms.
            </p>
          </Section>

          <Section title="13. Contact">
            <p>
              Questions about these Terms? Email us at{' '}
              <a href="mailto:safdarayub@gmail.com" className="text-[#1E40AF] underline">
                safdarayub@gmail.com
              </a>
              .
            </p>
          </Section>
        </div>
      </main>
      <FooterSection />
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="mb-4 text-xl font-semibold text-gray-900">{title}</h2>
      <div className="space-y-0 text-[15px] leading-relaxed text-gray-600">{children}</div>
    </section>
  )
}
